{
 "title": "Energy",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gas meter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") AND\n  name = 'gas.meter'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Electricity input/output",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  labels->'direction' AS metric,\n  -value\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") AND\n  name = 'electricity.power' AND\n  labels->'direction' = 'in'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  labels->'direction' AS metric,\n  value\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") AND\n  name = 'electricity.power' AND\n  labels->'direction' = 'out'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "ElectricityMeter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  labels->'tariff' AS metric,\n  value\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") AND\n  labels->'direction' = 'in' AND\n  name = 'electricity.meter'\nORDER BY 1,2"
    }
   ]
  }
 ]
}