version: '3.7'

services:
  postgres:
    image: docker.io/timescale/timescaledb:latest-pg14
    ports:
      - 5555:5432
    environment:
      - TIMESCALEDB_TELEMETRY=off
      - POSTGRES_USER=mqtt_to_pg
      - POSTGRES_PASSWORD=mqtt_to_pg
      - POSTGRES_DB=iot

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning